package ui;

import java.awt.image.BufferedImage;
import java.util.Calendar;
import seasonality.Crops;
import seasonality.Seasonality;

/**
 *
 * @author Torri
 */
public class StartupOptions extends javax.swing.JPanel {

    BufferedImage back;

    /**
     * Creates new form Options
     */
    public StartupOptions() {
        initComponents();
        done.addActionListener(Seasonality.bi);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crop = new javax.swing.JComboBox();
        inseason = new javax.swing.JComboBox();
        useThis = new javax.swing.JButton();
        done = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crop.setModel(new javax.swing.DefaultComboBoxModel(seasonality.Crops.editableCrops()));
        crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropActionPerformed(evt);
            }
        });
        add(crop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 251, 80));

        inseason.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "In Season", "Out Of Season" }));
        add(inseason, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 113, 134, 80));

        useThis.setText("Use this Property");
        useThis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useThisActionPerformed(evt);
            }
        });
        add(useThis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, 395, 65));

        done.setText("Done/Continue To Game");
        add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 113, 193, 163));
    }// </editor-fold>//GEN-END:initComponents

    private void cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropActionPerformed
        boolean season = Crops.values()[crop.getSelectedIndex()].inSeason((double) Calendar.getInstance().get(Calendar.MONTH));
        if (season) {
            inseason.setSelectedIndex(0);
        } else {
            inseason.setSelectedIndex(1);
        }
    }//GEN-LAST:event_cropActionPerformed

    private void useThisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useThisActionPerformed
        if (inseason.getSelectedIndex() == 1) {
            Crops.values()[crop.getSelectedIndex()].forceSeason(true);
        } else {
            Crops.values()[crop.getSelectedIndex()].forceSeason(false);
        }
    }//GEN-LAST:event_useThisActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox crop;
    public javax.swing.JButton done;
    private javax.swing.JComboBox inseason;
    private javax.swing.JButton useThis;
    // End of variables declaration//GEN-END:variables

}
