package ui;

import java.awt.image.BufferedImage;
import java.util.Calendar;
import seasonality.Crops;
import seasonality.Seasonality;

/**
 *
 * @author Torri
 */
public class StartupOptions extends javax.swing.JPanel {

    BufferedImage back;

    /**
     * Creates new form Options
     */
    public StartupOptions() {
        initComponents();
        done.addActionListener(Seasonality.bi);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crop = new javax.swing.JComboBox();
        inseason = new javax.swing.JComboBox();
        useThis = new javax.swing.JButton();
        done = new javax.swing.JButton();

        crop.setModel(new javax.swing.DefaultComboBoxModel(seasonality.Crops.values()));
        crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropActionPerformed(evt);
            }
        });

        inseason.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "In Season", "Out Of Season" }));

        useThis.setText("Use this Property");
        useThis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useThisActionPerformed(evt);
            }
        });

        done.setText("Done/Continue To Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(useThis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crop, 0, 251, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inseason, 0, 134, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crop, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(inseason))
                        .addGap(18, 18, 18)
                        .addComponent(useThis, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(324, 324, 324))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropActionPerformed
        boolean season = Crops.values()[crop.getSelectedIndex()].inSeason((double) Calendar.getInstance().get(Calendar.MONTH));
        if (season) {
            inseason.setSelectedIndex(0);
        } else {
            inseason.setSelectedIndex(1);
        }
    }//GEN-LAST:event_cropActionPerformed

    private void useThisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useThisActionPerformed
        if (inseason.getSelectedIndex() == 1) {
            Crops.values()[crop.getSelectedIndex()].forceSeason(true);
        } else {
            Crops.values()[crop.getSelectedIndex()].forceSeason(false);
        }
    }//GEN-LAST:event_useThisActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox crop;
    public javax.swing.JButton done;
    private javax.swing.JComboBox inseason;
    private javax.swing.JButton useThis;
    // End of variables declaration//GEN-END:variables

}
